### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by phentos** [phentos/does-rain-increase-unsheltered-homelessness#1]
- [x] #2
- [x] Define full extended date range based on available (SDDTP limiting)
- [x] Fetch new data
- [ ] Assess / implement merging old+new data
- [ ] Port *tl;dr* exposition from `Group001` to `fp-template`
- [ ] EDA for new data

**Comment by phentos** [comment]
[New data](https://downtownsandiego.org/wp-content/uploads/2024/03/February-2024-Unsheltered-Count-w-Maps.pdf) from SDDTP extends to Feb 24
